### ISSUE TITLE
bugs when make

### ISSUE THREAD

**Issue by cuge1995** [VimsLab/EllipsoidQuery#3]
[ 20%] Building NVCC (Device) object CMakeFiles/cuda_compile_1.dir/utils/csrc/cuda_compile_1_generated_sampling_gpu.cu.o
/home/cuge/Documents/point/EllipsoidQuery/RSCNNEQ/utils/csrc/sampling_gpu.cu:4:24: fatal error: cuda_utils.h: No such file or directory
compilation terminated.
CMake Error at cuda_compile_1_generated_sampling_gpu.cu.o.cmake:219 (message):
  Error generating
  /home/cuge/Documents/point/EllipsoidQuery/RSCNNEQ/build/CMakeFiles/cuda_compile_1.dir/utils/csrc/./cuda_compile_1_generated_sampling_gpu.cu.o

CMakeFiles/pointnet2_ext.dir/build.make:90: recipe for target 'CMakeFiles/cuda_compile_1.dir/utils/csrc/cuda_compile_1_generated_sampling_gpu.cu.o' failed
make[2]: *** [CMakeFiles/cuda_compile_1.dir/utils/csrc/cuda_compile_1_generated_sampling_gpu.cu.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/pointnet2_ext.dir/all' failed
make[1]: *** [CMakeFiles/pointnet2_ext.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by sheshap** [comment]
cinclude folder uploaded

**Comment by cuge1995** [comment]
thanks, it worked now
